# Generated by Django 5.0.4 on 2024-05-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_rename_product_cart_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderplaced",
            name="status",
            field=models.CharField(
                choices=[
                    ("Accepted", "Accepted"),
                    ("Packed", "Packed"),
                    ("On The Way", "On The Way"),
                    ("Delivery completed", "delivery completed"),
                    ("Cancel", "Cancel"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
    ]
