# Generated by Django 5.0.3 on 2024-05-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="availability",
            field=models.CharField(
                choices=[("IN STOCK", "IN STOCK"), ("SOLD OUT", "SOLD OUT")],
                default="IN_STOCK",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="spec",
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
